<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf67791e751e6b9ba4fcb5743076b5541
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf67791e751e6b9ba4fcb5743076b5541::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf67791e751e6b9ba4fcb5743076b5541::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf67791e751e6b9ba4fcb5743076b5541::$classMap;

        }, null, ClassLoader::class);
    }
}
